apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080 # Update this to the desired port
      targetPort: 8080
  type: LoadBalancer